yarnPath: .yarn/releases/yarn-4.0.2.cjs
nodeLinker: node-modules

npmScopes:
  taigawada:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_PACKAGE_TOKEN}"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"
