import { createTodaySales } from "./orders_create";
import { format } from "date-fns";
import { convertToTimeZone } from "date-fns-timezone";

test("createTodaysSales", async () => {
  const S = "0123456789";
  const orderId = `${S.slice(1, 10)[Math.floor(Math.random() * 9)]}${[...Array(12)].map(() => S[Math.floor(Math.random() * 10)]).join("")}`;
  const samplePayload = {
    id: parseInt(orderId),
    admin_graphql_api_id: `gid://shopify/Order/${orderId}`,
    app_id: null,
    browser_ip: null,
    buyer_accepts_marketing: true,
    cancel_reason: "customer",
    cancelled_at: "2025-02-09T18:20:31+09:00",
    cart_token: null,
    checkout_id: null,
    checkout_token: null,
    client_details: null,
    closed_at: null,
    confirmation_number: null,
    confirmed: false,
    contact_email: "jon@example.com",
    created_at: format(
      convertToTimeZone(new Date(), { timeZone: "Asia/Tokyo" }),
      "yyyy-MM-dd'T'HH:mm'Z+09:00'",
    ),
    currency: "JPY",
    current_shipping_price_set: {
      shop_money: {
        amount: "0",
        currency_code: "JPY",
      },
      presentment_money: {
        amount: "0",
        currency_code: "JPY",
      },
    },
    current_subtotal_price: "4000",
    current_subtotal_price_set: {
      shop_money: {
        amount: "4000",
        currency_code: "JPY",
      },
      presentment_money: {
        amount: "4000",
        currency_code: "JPY",
      },
    },
    current_total_additional_fees_set: null,
    current_total_discounts: "0",
    current_total_discounts_set: {
      shop_money: {
        amount: "0",
        currency_code: "JPY",
      },
      presentment_money: {
        amount: "0",
        currency_code: "JPY",
      },
    },
    current_total_duties_set: null,
    current_total_price: "4000",
    current_total_price_set: {
      shop_money: {
        amount: "4000",
        currency_code: "JPY",
      },
      presentment_money: {
        amount: "4000",
        currency_code: "JPY",
      },
    },
    current_total_tax: "0",
    current_total_tax_set: {
      shop_money: {
        amount: "0",
        currency_code: "JPY",
      },
      presentment_money: {
        amount: "0",
        currency_code: "JPY",
      },
    },
    customer_locale: "ja",
    device_id: null,
    discount_codes: [],
    duties_included: false,
    email: "jon@example.com",
    estimated_taxes: false,
    financial_status: "voided",
    fulfillment_status: "null",
    landing_site: null,
    landing_site_ref: null,
    location_id: null,
    merchant_business_entity_id: "MTYyMzkzMzE5Njc3",
    merchant_of_record_app_id: null,
    name: "#9999",
    note: null,
    note_attributes: [],
    number: 234,
    order_number: 1234,
    order_status_url:
      "https://chocolatlumiere.com/62393319677/orders/123456abcd/authenticate?key=abcdefg",
    original_total_additional_fees_set: null,
    original_total_duties_set: null,
    payment_gateway_names: ["visa", "bogus"],
    phone: null,
    po_number: null,
    presentment_currency: "JPY",
    processed_at: "2025-02-09T18:20:31+09:00",
    reference: null,
    referring_site: null,
    source_identifier: null,
    source_name: "web",
    source_url: null,
    subtotal_price: "3990",
    subtotal_price_set: {
      shop_money: {
        amount: "3990",
        currency_code: "JPY",
      },
      presentment_money: {
        amount: "3990",
        currency_code: "JPY",
      },
    },
    tags: "tag1, tag2",
    tax_exempt: false,
    tax_lines: [],
    taxes_included: false,
    test: true,
    token: "123456abcd",
    total_cash_rounding_payment_adjustment_set: {
      shop_money: {
        amount: "0",
        currency_code: "JPY",
      },
      presentment_money: {
        amount: "0",
        currency_code: "JPY",
      },
    },
    total_cash_rounding_refund_adjustment_set: {
      shop_money: {
        amount: "0",
        currency_code: "JPY",
      },
      presentment_money: {
        amount: "0",
        currency_code: "JPY",
      },
    },
    total_discounts: "20",
    total_discounts_set: {
      shop_money: {
        amount: "20",
        currency_code: "JPY",
      },
      presentment_money: {
        amount: "20",
        currency_code: "JPY",
      },
    },
    total_line_items_price: "4000",
    total_line_items_price_set: {
      shop_money: {
        amount: "4000",
        currency_code: "JPY",
      },
      presentment_money: {
        amount: "4000",
        currency_code: "JPY",
      },
    },
    total_outstanding: "4000",
    total_price: "3990",
    total_price_set: {
      shop_money: {
        amount: "3990",
        currency_code: "JPY",
      },
      presentment_money: {
        amount: "3990",
        currency_code: "JPY",
      },
    },
    total_shipping_price_set: {
      shop_money: {
        amount: "10",
        currency_code: "JPY",
      },
      presentment_money: {
        amount: "10",
        currency_code: "JPY",
      },
    },
    total_tax: "0",
    total_tax_set: {
      shop_money: {
        amount: "0",
        currency_code: "JPY",
      },
      presentment_money: {
        amount: "0",
        currency_code: "JPY",
      },
    },
    total_tip_received: "0",
    total_weight: 0,
    updated_at: "2025-02-09T18:20:31+09:00",
    user_id: null,
    billing_address: {
      first_name: "太郎",
      address1: "出荷通り",
      phone: "555-555-SHIP",
      city: "横浜市",
      zip: "221-0054",
      province: "Tokyo",
      country: "Japan",
      last_name: "山田",
      address2: null,
      company: "運送会社",
      latitude: null,
      longitude: null,
      name: "山田太郎",
      country_code: "JP",
      province_code: "JP-13",
    },
    customer: {
      id: 115310627314723950,
      email: "john@example.com",
      created_at: null,
      updated_at: null,
      first_name: "太郎",
      last_name: "山田",
      state: "disabled",
      note: null,
      verified_email: true,
      multipass_identifier: null,
      tax_exempt: false,
      phone: null,
      currency: "JPY",
      tax_exemptions: [],
      admin_graphql_api_id: "gid://shopify/Customer/115310627314723954",
      default_address: {
        id: 715243470612851200,
        customer_id: 115310627314723950,
        first_name: null,
        last_name: null,
        company: null,
        address1: "123 Elm St.",
        address2: null,
        city: "Ottawa",
        province: "Ontario",
        country: "Canada",
        zip: "K2H7A8",
        phone: "123-123-1234",
        name: "",
        province_code: "ON",
        country_code: "CA",
        country_name: "Canada",
        default: true,
      },
    },
    discount_applications: [],
    fulfillments: [],
    line_items: [
      {
        id: 866550311766439000,
        admin_graphql_api_id: "gid://shopify/LineItem/866550311766439020",
        attributed_staffs: [
          {
            id: "gid://shopify/StaffMember/902541635",
            quantity: 1,
          },
        ],
        current_quantity: 1,
        fulfillable_quantity: 1,
        fulfillment_service: "manual",
        fulfillment_status: "null",
        gift_card: false,
        grams: 150,
        name: "【数量限定】しょこるみストラップ",
        price: "2000",
        price_set: {
          shop_money: {
            amount: "2000",
            currency_code: "JPY",
          },
          presentment_money: {
            amount: "2000",
            currency_code: "JPY",
          },
        },
        product_exists: true,
        product_id: 7564452921597,
        properties: [],
        quantity: 1,
        requires_shipping: true,
        sales_line_item_group_id: null,
        sku: "",
        taxable: true,
        title: "【数量限定】しょこるみストラップ",
        total_discount: "0",
        total_discount_set: {
          shop_money: {
            amount: "0",
            currency_code: "JPY",
          },
          presentment_money: {
            amount: "0",
            currency_code: "JPY",
          },
        },
        variant_id: 42443672027389,
        variant_inventory_management: "shopify",
        variant_title: null,
        vendor: null,
        tax_lines: [],
        duties: [],
        discount_allocations: [],
      },
      {
        id: 141249953214522980,
        admin_graphql_api_id: "gid://shopify/LineItem/141249953214522974",
        attributed_staffs: [],
        current_quantity: 1,
        fulfillable_quantity: 1,
        fulfillment_service: "manual",
        fulfillment_status: "null",
        gift_card: false,
        grams: 300,
        name: "【数量限定】三銃士マフラータオル",
        price: "2000",
        price_set: {
          shop_money: {
            amount: "2000",
            currency_code: "JPY",
          },
          presentment_money: {
            amount: "2000",
            currency_code: "JPY",
          },
        },
        product_exists: true,
        product_id: 7571311034621,
        properties: [],
        quantity: 1,
        requires_shipping: true,
        sales_line_item_group_id: null,
        sku: "",
        taxable: true,
        title: "【数量限定】三銃士マフラータオル",
        total_discount: "0",
        total_discount_set: {
          shop_money: {
            amount: "0",
            currency_code: "JPY",
          },
          presentment_money: {
            amount: "0",
            currency_code: "JPY",
          },
        },
        variant_id: 42466709700861,
        variant_inventory_management: "shopify",
        variant_title: null,
        vendor: null,
        tax_lines: [],
        duties: [],
        discount_allocations: [],
      },
    ],
    payment_terms: null,
    refunds: [],
    shipping_address: {
      first_name: "太郎",
      address1: "出荷通り",
      phone: "555-555-SHIP",
      city: "横浜市",
      zip: "221-0054",
      province: "Tokyo",
      country: "Japan",
      last_name: "山田",
      address2: null,
      company: "運送会社",
      latitude: null,
      longitude: null,
      name: "山田太郎",
      country_code: "JP",
      province_code: "JP-13",
    },
    shipping_lines: [
      {
        id: 271878346596884000,
        carrier_identifier: null,
        code: null,
        current_discounted_price_set: {
          shop_money: {
            amount: "0",
            currency_code: "JPY",
          },
          presentment_money: {
            amount: "0",
            currency_code: "JPY",
          },
        },
        discounted_price: "10",
        discounted_price_set: {
          shop_money: {
            amount: "10",
            currency_code: "JPY",
          },
          presentment_money: {
            amount: "10",
            currency_code: "JPY",
          },
        },
        is_removed: false,
        phone: null,
        price: "10",
        price_set: {
          shop_money: {
            amount: "10",
            currency_code: "JPY",
          },
          presentment_money: {
            amount: "10",
            currency_code: "JPY",
          },
        },
        requested_fulfillment_service_id: null,
        source: "shopify",
        title: "Generic Shipping",
        tax_lines: [],
        discount_allocations: [],
      },
    ],
    returns: [],
  };
  await createTodaySales(samplePayload);
});
